workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.course_app"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build apk
        script: flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
    android:
      gradle:
        gradle_args: "-Dorg.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" 